
FROM python:3.8
ENV PYTHONUNBUFFERED=1
WORKDIR /app

COPY requirements.txt requirements.txt
RUN apt update
RUN apt upgrade -y
# apt install libdbus-1-3
RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000
