# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\user\Desktop\testing_app\test_admin\admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1154, 721)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.test_box = QtWidgets.QGroupBox(self.centralwidget)
        self.test_box.setGeometry(QtCore.QRect(0, 0, 1171, 721))
        self.test_box.setStyleSheet("")
        self.test_box.setTitle("")
        self.test_box.setObjectName("test_box")
        self.question_text = QtWidgets.QLabel(self.test_box)
        self.question_text.setGeometry(QtCore.QRect(80, 40, 1061, 131))
        self.question_text.setMinimumSize(QtCore.QSize(1061, 0))
        self.question_text.setMaximumSize(QtCore.QSize(1061, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.question_text.setFont(font)
        self.question_text.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"padding-left:10px")
        self.question_text.setText("")
        self.question_text.setWordWrap(True)
        self.question_text.setObjectName("question_text")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.test_box)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(80, 190, 1071, 461))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.question_list_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.question_list_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.question_list_layout.setContentsMargins(0, 0, 0, 0)
        self.question_list_layout.setSpacing(6)
        self.question_list_layout.setObjectName("question_list_layout")
        self.question_box_1 = QtWidgets.QHBoxLayout()
        self.question_box_1.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.question_box_1.setObjectName("question_box_1")
        self.answer_var_1 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.answer_var_1.sizePolicy().hasHeightForWidth())
        self.answer_var_1.setSizePolicy(sizePolicy)
        self.answer_var_1.setMinimumSize(QtCore.QSize(1040, 108))
        self.answer_var_1.setMaximumSize(QtCore.QSize(950, 16777215))
        self.answer_var_1.setMouseTracking(False)
        self.answer_var_1.setAutoFillBackground(False)
        self.answer_var_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"padding-left:10px")
        self.answer_var_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.answer_var_1.setText("")
        self.answer_var_1.setTextFormat(QtCore.Qt.AutoText)
        self.answer_var_1.setWordWrap(True)
        self.answer_var_1.setObjectName("answer_var_1")
        self.question_box_1.addWidget(self.answer_var_1)
        self.choose_answer_1 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_answer_1.sizePolicy().hasHeightForWidth())
        self.choose_answer_1.setSizePolicy(sizePolicy)
        self.choose_answer_1.setMaximumSize(QtCore.QSize(16, 16777215))
        self.choose_answer_1.setText("")
        self.choose_answer_1.setObjectName("choose_answer_1")
        self.question_box_1.addWidget(self.choose_answer_1)
        self.question_list_layout.addLayout(self.question_box_1)
        self.question_box_2 = QtWidgets.QHBoxLayout()
        self.question_box_2.setObjectName("question_box_2")
        self.answer_var_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.answer_var_2.sizePolicy().hasHeightForWidth())
        self.answer_var_2.setSizePolicy(sizePolicy)
        self.answer_var_2.setMinimumSize(QtCore.QSize(1040, 108))
        self.answer_var_2.setMaximumSize(QtCore.QSize(950, 16777215))
        self.answer_var_2.setMouseTracking(True)
        self.answer_var_2.setAutoFillBackground(False)
        self.answer_var_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"padding-left:10px")
        self.answer_var_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.answer_var_2.setText("")
        self.answer_var_2.setTextFormat(QtCore.Qt.AutoText)
        self.answer_var_2.setWordWrap(True)
        self.answer_var_2.setObjectName("answer_var_2")
        self.question_box_2.addWidget(self.answer_var_2)
        self.choose_answer_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_answer_2.sizePolicy().hasHeightForWidth())
        self.choose_answer_2.setSizePolicy(sizePolicy)
        self.choose_answer_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.choose_answer_2.setText("")
        self.choose_answer_2.setObjectName("choose_answer_2")
        self.question_box_2.addWidget(self.choose_answer_2)
        self.question_list_layout.addLayout(self.question_box_2)
        self.question_box_3 = QtWidgets.QHBoxLayout()
        self.question_box_3.setObjectName("question_box_3")
        self.answer_var_3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.answer_var_3.sizePolicy().hasHeightForWidth())
        self.answer_var_3.setSizePolicy(sizePolicy)
        self.answer_var_3.setMinimumSize(QtCore.QSize(1040, 108))
        self.answer_var_3.setMaximumSize(QtCore.QSize(950, 16777215))
        self.answer_var_3.setAutoFillBackground(False)
        self.answer_var_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"padding-left:10px")
        self.answer_var_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.answer_var_3.setText("")
        self.answer_var_3.setTextFormat(QtCore.Qt.AutoText)
        self.answer_var_3.setWordWrap(True)
        self.answer_var_3.setObjectName("answer_var_3")
        self.question_box_3.addWidget(self.answer_var_3)
        self.choose_answer_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_answer_3.sizePolicy().hasHeightForWidth())
        self.choose_answer_3.setSizePolicy(sizePolicy)
        self.choose_answer_3.setMaximumSize(QtCore.QSize(16, 16777215))
        self.choose_answer_3.setText("")
        self.choose_answer_3.setObjectName("choose_answer_3")
        self.question_box_3.addWidget(self.choose_answer_3)
        self.question_list_layout.addLayout(self.question_box_3)
        self.question_box_4 = QtWidgets.QHBoxLayout()
        self.question_box_4.setObjectName("question_box_4")
        self.answer_var_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.answer_var_4.sizePolicy().hasHeightForWidth())
        self.answer_var_4.setSizePolicy(sizePolicy)
        self.answer_var_4.setMinimumSize(QtCore.QSize(1040, 108))
        self.answer_var_4.setMaximumSize(QtCore.QSize(950, 16777215))
        self.answer_var_4.setAutoFillBackground(False)
        self.answer_var_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"padding-left:10px")
        self.answer_var_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.answer_var_4.setText("")
        self.answer_var_4.setTextFormat(QtCore.Qt.AutoText)
        self.answer_var_4.setWordWrap(True)
        self.answer_var_4.setObjectName("answer_var_4")
        self.question_box_4.addWidget(self.answer_var_4)
        self.choose_answer_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_answer_4.sizePolicy().hasHeightForWidth())
        self.choose_answer_4.setSizePolicy(sizePolicy)
        self.choose_answer_4.setMaximumSize(QtCore.QSize(16, 16777215))
        self.choose_answer_4.setText("")
        self.choose_answer_4.setObjectName("choose_answer_4")
        self.question_box_4.addWidget(self.choose_answer_4)
        self.question_list_layout.addLayout(self.question_box_4)
        self.next_question = QtWidgets.QPushButton(self.test_box)
        self.next_question.setGeometry(QtCore.QRect(880, 660, 231, 41))
        self.next_question.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_question.setStyleSheet("    QPushButton {\n"
"        background-color: #0171CA;\n"
"        color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background: rgba(0,0,0,0);\n"
"        color: #3a7999;\n"
"         border : 2px solid ;\n"
"        border-color: #0171CA;\n"
"    }")
        self.next_question.setObjectName("next_question")
        self.qty_question_label = QtWidgets.QLabel(self.test_box)
        self.qty_question_label.setGeometry(QtCore.QRect(800, 670, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qty_question_label.setFont(font)
        self.qty_question_label.setObjectName("qty_question_label")
        self.time_counter = QtWidgets.QLabel(self.test_box)
        self.time_counter.setGeometry(QtCore.QRect(440, 670, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.time_counter.setFont(font)
        self.time_counter.setText("")
        self.time_counter.setObjectName("time_counter")
        self.previous_question = QtWidgets.QPushButton(self.test_box)
        self.previous_question.setGeometry(QtCore.QRect(80, 660, 231, 41))
        self.previous_question.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.previous_question.setStyleSheet("    QPushButton {\n"
"        background-color: #0171CA;\n"
"        color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background: rgba(0,0,0,0);\n"
"        color: #3a7999;\n"
"         border : 2px solid ;\n"
"        border-color: #0171CA;\n"
"    }")
        self.previous_question.setObjectName("previous_question")
        self.test_result_box_menue = QtWidgets.QGroupBox(self.centralwidget)
        self.test_result_box_menue.setGeometry(QtCore.QRect(0, 0, 1171, 721))
        self.test_result_box_menue.setStyleSheet("")
        self.test_result_box_menue.setTitle("")
        self.test_result_box_menue.setObjectName("test_result_box_menue")
        self.tests_list = QtWidgets.QListWidget(self.test_result_box_menue)
        self.tests_list.setGeometry(QtCore.QRect(30, 80, 371, 601))
        self.tests_list.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"padding-left:10px")
        self.tests_list.setObjectName("tests_list")
        self.folder_list = QtWidgets.QComboBox(self.test_result_box_menue)
        self.folder_list.setGeometry(QtCore.QRect(30, 20, 371, 41))
        self.folder_list.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.folder_list.setEditable(False)
        self.folder_list.setObjectName("folder_list")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.test_result_box_menue)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(430, 20, 681, 651))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.fio_label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.fio_label.setFont(font)
        self.fio_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"padding-left:10px")
        self.fio_label.setText("")
        self.fio_label.setObjectName("fio_label")
        self.verticalLayout_4.addWidget(self.fio_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"padding-left:10px")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.type_test_result = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.type_test_result.setFont(font)
        self.type_test_result.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"padding-left:10px")
        self.type_test_result.setText("")
        self.type_test_result.setObjectName("type_test_result")
        self.horizontalLayout_3.addWidget(self.type_test_result)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"padding-left:10px")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_8.addWidget(self.label_4)
        self.time_wasted_result = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.time_wasted_result.setFont(font)
        self.time_wasted_result.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"padding-left:10px")
        self.time_wasted_result.setText("")
        self.time_wasted_result.setObjectName("time_wasted_result")
        self.horizontalLayout_8.addWidget(self.time_wasted_result)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"padding-left:10px")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.correct_answers_result = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.correct_answers_result.setFont(font)
        self.correct_answers_result.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"padding-left:10px")
        self.correct_answers_result.setText("")
        self.correct_answers_result.setObjectName("correct_answers_result")
        self.horizontalLayout_9.addWidget(self.correct_answers_result)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"padding-left:10px")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.grade_label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.grade_label.setFont(font)
        self.grade_label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"padding-left:10px")
        self.grade_label.setText("")
        self.grade_label.setObjectName("grade_label")
        self.horizontalLayout_10.addWidget(self.grade_label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.get_export_result = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_export_result.sizePolicy().hasHeightForWidth())
        self.get_export_result.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.get_export_result.setFont(font)
        self.get_export_result.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.get_export_result.setStyleSheet("    QPushButton {\n"
"        background-color: #0171CA;\n"
"        color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background: rgba(0,0,0,0);\n"
"        color: #3a7999;\n"
"         border : 2px solid ;\n"
"        border-color: #0171CA;\n"
"    }")
        self.get_export_result.setObjectName("get_export_result")
        self.verticalLayout_4.addWidget(self.get_export_result)
        self.get_result_from_result = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.get_result_from_result.sizePolicy().hasHeightForWidth())
        self.get_result_from_result.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.get_result_from_result.setFont(font)
        self.get_result_from_result.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.get_result_from_result.setStyleSheet("    QPushButton {\n"
"        background-color: #0171CA;\n"
"        color: rgb(255, 255, 255);\n"
"        border-radius: 10px;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background: rgba(0,0,0,0);\n"
"        color: #3a7999;\n"
"         border : 2px solid ;\n"
"        border-color: #0171CA;\n"
"    }")
        self.get_result_from_result.setObjectName("get_result_from_result")
        self.verticalLayout_4.addWidget(self.get_result_from_result)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.next_question.setText(_translate("MainWindow", "Следующий вопрос"))
        self.qty_question_label.setText(_translate("MainWindow", "0/0"))
        self.previous_question.setText(_translate("MainWindow", "Предыдущий вопрос"))
        self.label_3.setText(_translate("MainWindow", "Тип теста:"))
        self.label_4.setText(_translate("MainWindow", "Время:"))
        self.label_7.setText(_translate("MainWindow", "Правильных ответов:"))
        self.label_8.setText(_translate("MainWindow", "Оценка:"))
        self.get_export_result.setText(_translate("MainWindow", "Выгрузить Отчёт"))
        self.get_result_from_result.setText(_translate("MainWindow", "Посмотреть результат"))
